### ISSUE TITLE
Issues with LiquidStation (Critical)

### ISSUE THREAD

**Issue by chadthundercock69** [SwiGs1/LiquidStation-13#31]
# Issues with LiquidStation:

Malformed changelog entries in PRs

Trek chems incorrectly added back (cobbychems not removed, trekchem recipes not added, medkits not changed, vendors not changed, interactions not changed, sleepers not changed etc etc)

Literally reverted their broken removal of trekchems because it was so shit

Configuration Files commited to repository (why)

Round ID always NULL

Webedits [VERIFIED]

Roundend sounds incorrectly added with spaces in their names, sound files not actually added in the first place, only edited ticker.dm (ENJOY THOSE RUNTIMES)

Removed Gender Neutral option without editing player configuration options and ingame interactions (again, ENJOY THOSE RUNTIMES)

motd.txt incorrectly formatted with HTML (NEW LINES IN HTML DON'T DISPLAY AS NEW LINES)

Incorrectly added species datums with no interactions

Don't understand how to configure the server to appear on the hub

Modularized code for vampires but didn't actually remove the old code from the main repo (ENJOY THOSE RUNTIMES *AND* CONFLICTS)

Have a changes.txt file in their modularized code folder but don't actually use it

Committing directly to the master branch with major untested code changes

"""Fixed""" vampire bite """bug""" that occured because they LITERALLY FORGOT A PROC

Will probably put their database username and password on github if they're smart enough to work out how to setup MySQL

All the code is copypasted instead of just checking out branches

No attempt to update and merge bug fixes and security patches from upstream (EVEN HIPPIE DOES THIS)

Manually labeling all their PRs instead of getting a bot to do it

Has a modularized code folder but are still adding terminators to the base repo

And worst of all, they got bored of it

**Comment by SwiGs1** [comment]
Bahahaha nice one McFag

**Comment by waterwater1212** [comment]
issue closed.... complete and utter nonsense... porting to austation on june 1st...
